# Generated by Django 4.2.20 on 2025-05-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'Inactive')], default=2),
        ),
    ]
