# Generated by Django 4.2.20 on 2025-05-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcategory_slug_alter_postmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='slug',
        ),
    ]
